### ISSUE TITLE
AUTOMATIC BATCH PROCESS - Create service attaches metadata to file

### ISSUE THREAD

**Issue by KaylieGreen1607** [MHRA/products#426]
### User want
As a user
I want to see up to date documents on the products website
So I can make informed decisions

**Customer acceptance criteria** 

**Technical acceptance criteria**
Create service attaches metadata from the received message to a retrieved file.
A lot of this code can be lifted from the existing import process.

**Data acceptance criteria**

**Testing acceptance criteria** 

**Size**
S

**Value**

**Effort**

### Exit Criteria met 
- [x] Backlog
- [x] Discovery
- [x] DUXD
- [x] Development 
- [ ] Quality Assurance 
- [ ] Release and Validate

**Comment by craiga** [comment]
While testing locally, the following request…

```
## Create (JSON)
curl -X "POST" "http://localhost:8000/documents" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -u 'craiga:password' \
     -d $'{
  "author": "author",
  "products": [
    "products"
  ],
  "id": "id123",
  "keywords": [
    "keywords"
  ],
  "file_source": "Sentinel",
  "file_path": "hello.txt",
  "type": "PIL",
  "pl_number": "PL 12345/6789",
  "name": "name",
  "active_substances": [
    "substance a",
    "subtstance\\nb",
    "café",
    "zoë"
  ]
}'
```

resulted in a panic in the create worker:

```
{"timestamp":"2020-03-23T15:59:11.863414+00:00 ","level":"INFO","span":{"name":"create_service_worker","state_manager":"StateManager { client: Client { connection_info: ConnectionInfo { addr: Tcp(\"127.0.0.1\", 6379), db: 0, passwd: None } } }","time_to_wait":"5s"},"target":"doc_index_updater::create_manager::sftp_client","message":"\"hello.txt\""}
{"timestamp":"2020-03-23T15:59:11.864636+00:00 ","level":"INFO","span":{"name":"create_service_worker","state_manager":"StateManager { client: Client { connection_info: ConnectionInfo { addr: Tcp(\"127.0.0.1\", 6379), db: 0, passwd: None } } }","time_to_wait":"5s"},"target":"doc_index_updater::create_manager::sftp_client","message":"File retrieved from SFTP at hello.txt (14 bytes) "}
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/craiga/.cargo/git/checkouts/azuresdkforrust-0886d4f3ee80caf0/ce612fd/azure_sdk_storage_core/src/rest_client.rs:415:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by craiga** [comment]
The above issue was caused by a malformed `STORAGE_MASTER_KEY` environment variable. Instead of `STORAGE_MASTER_KEY=THEVALUE`, I had `STORAGE_MASTER_KEY==THEVALUE`.

**Comment by craiga** [comment]
Verified that active substance names are parsed as expected except for when they contain a non-ASCII character.

For example, in the example posted above, both "SUBSTANCE A" and "SUBSTANCE B" were attached to the product, but "ZOË" and "CAFÉ" were not.

Is there a chance that active substances will contain characters outside of the standard ASCII character set?

**Comment by rjkerrison** [comment]
https://github.com/MHRA/products/pull/499#discussion_r391699360

I knew that sounded familiar. I should've been stricter with that question back in the original, back in the original, back in the original PR.

**Comment by craiga** [comment]
Including active substances with accented characters now results in a panic in the create worker.

```
curl -X "POST" "http://localhost:8000/documents" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -u 'craiga:password' \
     -d $'{
  "author": "author",
  "products": [
    "products"
  ],
  "id": "id123",
  "keywords": [
    "keywords"
  ],
  "file_source": "Sentinel",
  "file_path": "craiga.id.au/emoji.pdf",
  "type": "PIL",
  "pl_number": "PL123456788",
  "name": "name",
  "active_substances": [
    "substance a",
    "subtstance\\nb",
    "café",
    "zoë"
  ]
}'
```

Result (which includes some debugging output I've added):

```
2020-03-25T10:54:29.425021+00:00   INFO create_service_worker{time_to_wait=1s state_manager=StateManager { client: Client { connection_info: ConnectionInfo { addr: Tcp("127.0.0.1", 6379), db: 0, passwd: None } } }}: doc_index_updater::service_bus_client: Message found perfectly parseable ("{\"job_id\":\"fb1263ae-efa0-430e-93f1-cf7cb2447f71\",\"document\":{\"id\":\"id123\",\"name\":\"name\",\"type\":\"PIL\",\"author\":\"author\",\"products\":[\"products\"],\"keywords\":[\"keywords\"],\"pl_number\":\"PL123456788\",\"active_substances\":[\"substance a\",\"subtstance\\nb\",\"café\"],\"file_source\":\"Sentinel\",\"file_path\":\"craiga.id.au/emoji.pdf\"}}").
Ok("{\"job_id\":\"fb1263ae-efa0-430e-93f1-cf7cb2447f71\",\"document\":{\"id\":\"id123\",\"name\":\"name\",\"type\":\"PIL\",\"author\":\"author\",\"products\":[\"products\"],\"keywords\":[\"keywords\"],\"pl_number\":\"PL123456788\",\"active_substances\":[\"substance a\",\"subtstance\\nb\",\"café\"],\"file_source\":\"Sentinel\",\"file_path\":\"craiga.id.au/emoji.pdf\"}}")
2020-03-25T10:54:29.425302+00:00   INFO create_service_worker{time_to_wait=1s state_manager=StateManager { client: Client { connection_info: ConnectionInfo { addr: Tcp("127.0.0.1", 6379), db: 0, passwd: None } } }}: doc_index_updater::create_manager: Message received: CreateMessage { job_id: fb1263ae-efa0-430e-93f1-cf7cb2447f71, document: Document { id: "id123", name: "name", document_type: Pil, author: "author", products: ["products"], keywords: Some(["keywords"]), pl_number: "PL123456788", active_substances: ["substance a", "subtstance\nb", "café"], file_source: Sentinel, file_path: "craiga.id.au/emoji.pdf" } } 
2020-03-25T10:54:30.442092+00:00   INFO create_service_worker{time_to_wait=1s state_manager=StateManager { client: Client { connection_info: ConnectionInfo { addr: Tcp("127.0.0.1", 6379), db: 0, passwd: None } } }}: doc_index_updater::create_manager::sftp_client: "craiga.id.au/emoji.pdf"
2020-03-25T10:54:30.444575+00:00   INFO create_service_worker{time_to_wait=1s state_manager=StateManager { client: Client { connection_info: ConnectionInfo { addr: Tcp("127.0.0.1", 6379), db: 0, passwd: None } } }}: doc_index_updater::create_manager::sftp_client: File retrieved from SFTP at craiga.id.au/emoji.pdf (31253 bytes) 
2020-03-25T10:54:30.453939+00:00   INFO create_service_worker{time_to_wait=1s state_manager=StateManager { client: Client { connection_info: ConnectionInfo { addr: Tcp("127.0.0.1", 6379), db: 0, passwd: None } } }}: doc_index_updater::create_manager: Metadata hash map: {"file_name": "id123", "title": "name", "facets": "[\"C\",\"C, CAFÉ\",\"C, CAFÉ, PRODUCTS\",\"S\",\"S, SUBSTANCE A\",\"S, SUBSTANCE A, PRODUCTS\",\"S, SUBTSTANCE\\nB\",\"S, SUBTSTANCE\\nB, PRODUCTS\"]", "substance_name": "[\"SUBSTANCE A\",\"SUBTSTANCE\\nB\",\"CAFÉ\"]", "keywords": "keywords", "author": "author", "pl_number": "[]", "product_name": "[\"PRODUCTS\"]", "doc_type": "Pil"}
2020-03-25T10:54:30.454053+00:00   INFO create_service_worker{time_to_wait=1s state_manager=StateManager { client: Client { connection_info: ConnectionInfo { addr: Tcp("127.0.0.1", 6379), db: 0, passwd: None } } }}: doc_index_updater::create_manager: About to put blob
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/craiga/.cargo/git/checkouts/azuresdkforrust-0886d4f3ee80caf0/ce612fd/azure_sdk_storage_core/src/rest_client.rs:415:17
```

**Comment by craiga** [comment]
The same happens if product name contains an accented character, and it's likely to effect more fields.

**Comment by rjkerrison** [comment]
As discussed with @craiga, I'll correct the panicking asap by removing these non-ASCII strings as we have done with the importer previously. #551 captures a wider need to support these.
